In [27]:
import numpy as np
import tensorflow as tf
from keras.models import load_model
import os
import pandas as pd

In [19]:
array = np.asarray([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [20]:
array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
array = array[None,:]

In [45]:
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
array.dtype

dtype('int32')

In [23]:
array.ndim

2

In [24]:
model = load_model(os.getcwd()+"/BankApp/model")

In [25]:
model

In [26]:
model.predict(array)

1/1 [==============================] - 0s 369ms/step


array([[0.00239567]], dtype=float32)

In [31]:
df = pd.read_csv("TestValues.csv")

In [32]:
num = np.asarray(df)

In [50]:
num = array[None:]

In [51]:
num

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
model = load_model(os.getcwd()+"/BankApp/model")

In [53]:
model.predict(num)

1/1 [==============================] - 0s 316ms/step


array([[0.00239567]], dtype=float32)

In [54]:
prediction = np.argmax(model.predict(num))
prediction

1/1 [==============================] - 0s 20ms/step


0

In [56]:
np.where(model.predict(num) >=0.5,1,0)

1/1 [==============================] - 0s 277ms/step


array([[0]])

In [40]:
if prediction == 1:
    outcome = "SUBSCRIBE TO A TERM DEPOSIT"
else:
    outcome = "NOT SUBSCRIBE TO A TERM DEPOSIT"
    
outcome

'NOT SUBSCRIBE TO A TERM DEPOSIT'

In [43]:
if pred == 1:
    outcome = "SUBSCRIBE TO A TERM DEPOSIT"
else:
    outcome = "NOT SUBSCRIBE TO A TERM DEPOSIT"
    
outcome

'SUBSCRIBE TO A TERM DEPOSIT'

In [59]:
location = "{}\\model".format(os.getcwd())

In [60]:
location

'C:\\Users\\anura\\Desktop\\CIS_Final_Exam-1\\model'